
import { messageFromError } from 'aeonvera/helpers/message-from-error';
import { module, test } from 'qunit';

module('Unit | Helper | message from error');

// Replace this with your real tests.
test('it works', function(assert) {
  let result = messageFromError([42]);
  assert.ok(result);
});

